
# Site settings

url: "http://nicklawls.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

baseurl: ""

google-tracking-id: "UA-68691916-1"

#############
# HTML Head #
#############

author: "Nicolas Lawler"
lang: "en"
title: "One who lawls"
favicon: "/img/alien_gray.ico"
description: "The blog and bio of Nicolas Lawler"
keywords: "nick, lawler, nicolas, blog, personal, jekyll, theme"

################
# Intro layout #
################

black-favicon: ""
background-img: ""
me-img: ""

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: True	# Shuffle the lines.
loop: True
loop-count:	1 # Set False for infinite loop, or set any number for finite loop.
type-speed:	8		# Default 10
start-delay: 400	# Default 200
delete-delay: 2000	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "Every improvement is necessiarily a change"
  - text: "Not every change is an improvement"


########
# Blog #
########

post-preview-words: 0

paginate: 10

fb-share: True
twitter-share: True
reddit-share: True
disqus-shortname: "licknawler"

###############
# Life Events #
###############

# TODO find a good image size

events:
  - image: ""
    date: "June 2015 - September 2015"
    description: "Interned in the Engineering department at j2 Global, built a REST API to streamline internal processes"
  - image: ""
    date: "April 2014"
    description: "Aged out of Pulse, managed to snag a gold medal"
  - image: ""
    date: "August 2013"
    description: "Ended 3 unforgetable summers on the road with the Bluecoats"
  - image: ""
    date: "May 2012"
    description: "Switched majors to Computer Science, began planning a post-band career"
  - image: ""
    date: "September 2010"
    description: "Enrolled at UC Riverside, achieved my goal of joining Pulse Percusion and the Bluecoats"
  - image: ""
    date: "2006 - 2010"
    description: "Attended high school, caught the drumline bug"
  - image: ""
    date: "1991"
    description: "Arrival on earth, located dwelling in Suburbia, USA"

# First image of the Career timeline
career-img: "/img/career/default.png"

##################
# Contact layout #
##################

email: lawler145@gmail.com

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "http://facebook.com/nicklawls"
  - title: "twitter"
    url: "http://twitter.com/licknalwer"
  - title: "github"
    url: "https://github.com/nicklawls"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Blog: 'blog'
  Career: 'career'
  Contact: 'contact'

# Pagination path
paginate_path: "blog/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
